version: '3'

services:
  bidirect-a:
    build:
      context: ./bidirect-a
      args:
        A_VERSION: ${A_VERSION}
    env_file: .env
    image: bidirect-a:${A_VERSION}
    container_name: bidirect-a
    ports:
      - "${A_PORT}:8080"
    networks:
      intra:
        aliases:
          - "bidirect-a.local"
    volumes:
      - /c/temp/logs/bidirect-a:/logs

  bidirect-b:
    build:
      context: ./bidirect-b
      args:
        B_VERSION: ${B_VERSION}
    env_file: .env
    image: bidirect-b:${B_VERSION}
    container_name: bidirect-b
    ports:
      - "${B_PORT}:8080"
    networks:
      intra:

networks:
  intra: