version: '3'

services:
  bidirect-a:
    build:
      context: ./bidirect-a
      args:
        A_VERSION: ${A_VERSION}
    env_file: .env
    image: bidirect-a:${A_VERSION}
    container_name: bidirect-a
    ports:
      - "${A_PORT}:8080"
#    networks:
#      intra:
#        aliases:
#          - "docker.local"
#    extra_hosts:
#      - "docker.local:192.168.99.100" #Docker Machine IP

  bidirect-b:
    build:
      context: ./bidirect-b
      args:
        B_VERSION: ${B_VERSION}
    env_file: .env
    image: bidirect-b:${B_VERSION}
    container_name: bidirect-b
    ports:
      - "${B_PORT}:8080"
#    networks:
#      intra:
    extra_hosts:
      - "docker.local:192.168.56.1" #Docker Machine IP

#networks:
#  intra:
